// <auto-generated />
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using EcuNexo.Business.Accounting.Repositories;
using EcuNexo.Business.Customers.Repositories;
using EcuNexo.Business.Ecommerce.Repositories;
using EcuNexo.Business.Inventory;
using EcuNexo.Business.Platform.Queries.GetDashboardAnalytics;
using EcuNexo.Business.Purchases.Repositories;
using EcuNexo.Business.RemisionGuides;
using EcuNexo.Business.Repairs.Repositories;
using EcuNexo.Business.Warehousing;
using EcuNexo.Core.Customers;
using EcuNexo.Core.RemisionGuides;
using EcuNexo.Core.Warehousing;
using NSubstitute;
using Xunit;

#nullable disable
#pragma warning disable IDE0005

namespace EcuNexo.Business.UnitTests.Platform;

public sealed class GetDashboardAnalyticsHandlerTests
{
    private readonly ICustomerRepository _customers = Substitute.For<ICustomerRepository>();
    private readonly IStockRepository _stocks = Substitute.For<IStockRepository>();
    private readonly IWarehouseRepository _warehouses = Substitute.For<IWarehouseRepository>();
    private readonly IRemisionGuideRepository _remisionGuides = Substitute.For<IRemisionGuideRepository>();
    private readonly IRepairEquipmentRepository _repairs = Substitute.For<IRepairEquipmentRepository>();
    private readonly IPurchaseRepository _purchases = Substitute.For<IPurchaseRepository>();
    private readonly IRepairBatchRepository _repairBatches = Substitute.For<IRepairBatchRepository>();
    private readonly IEcommerceOrderRepository _ecommerceOrders = Substitute.For<IEcommerceOrderRepository>();
    private readonly IExpenseTypeRepository _expenseTypes = Substitute.For<IExpenseTypeRepository>();
    private readonly IJournalEntryRepository _journalEntries = Substitute.For<IJournalEntryRepository>();
    private readonly IAccountRepository _accounts = Substitute.For<IAccountRepository>();

    private readonly GetDashboardAnalyticsHandler _handler;

    public GetDashboardAnalyticsHandlerTests()
    {
        _customers.ListByTenantAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult<IReadOnlyList<Customer>>([]));
        _warehouses.ListActiveByTenantAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromResult<IReadOnlyList<Warehouse>>([]));
        _remisionGuides.ListAsync(Arg.Any<Guid>(), null, null, null, null, Arg.Any<CancellationToken>())
            .Returns(Task.FromResult<IReadOnlyList<RemisionGuide>>([]));

        _handler = new GetDashboardAnalyticsHandler(
            _customers,
            _stocks,
            _warehouses,
            _remisionGuides,
            _repairs,
            _purchases,
            _repairBatches,
            _ecommerceOrders,
            _expenseTypes,
            _journalEntries,
            _accounts);
    }

    [Fact]
    public async Task Handle_ReturnsValidDashboardAnalytics_WithDefaultFallbackData()
    {
        // Arrange
        var tenantId = Guid.NewGuid();
        var query = new GetDashboardAnalyticsQuery(tenantId);

        // Act
        var result = await _handler.Handle(query, CancellationToken.None);

        // Assert
        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal(6, result.Value.SalesMonthlyTrend.Count);
        Assert.Equal(3, result.Value.SriStatusDistribution.Count);
        Assert.Equal(4, result.Value.CustomerTypeDistribution.Count);
        Assert.Equal(6, result.Value.PurchasesExpensesTrend.Count);
        Assert.Equal(4, result.Value.WarehouseStockDistribution.Count);
        Assert.Equal(3, result.Value.RemisionGuidesStatus.Count);
        Assert.Equal(3, result.Value.RepairStagesDistribution.Count);
        Assert.Equal(3, result.Value.FinancialBalance.Count);
        Assert.Equal(6, result.Value.TaxDeclarationsTrend.Count);
    }
}
