using EcuNexo.Business.Abstractions;
using EcuNexo.Business.Catalog;
using EcuNexo.Business.Catalog.Commands.CreateCatalogItem;
using EcuNexo.Business.Catalog.Commands.CreateCategory;
using EcuNexo.Business.Catalog.Commands.DeleteCatalogItemImage;
using EcuNexo.Business.Catalog.Commands.ReorderCatalogItemImages;
using EcuNexo.Business.Catalog.Commands.SetCatalogItemMainImage;
using EcuNexo.Business.Catalog.Commands.SoftDeleteCatalogItem;
using EcuNexo.Business.Catalog.Commands.SoftDeleteCategory;
using EcuNexo.Business.Catalog.Commands.UpdateCatalogItem;
using EcuNexo.Business.Catalog.Commands.UpdateCatalogItemImageAltText;
using EcuNexo.Business.Catalog.Commands.UpdateCategory;
using EcuNexo.Business.Catalog.Commands.UploadCatalogItemImage;
using EcuNexo.Business.Catalog.Images;
using EcuNexo.Business.Catalog.Queries.GetCatalogItem;
using EcuNexo.Business.Catalog.Queries.ListCatalogItems;
using EcuNexo.Business.Catalog.Queries.ListCategories;
using EcuNexo.Business.Storage;
using Microsoft.Extensions.Configuration;
using EcuNexo.Business.Identity;
using EcuNexo.Business.Inventory;
using EcuNexo.Business.Inventory.Commands.ApplyAuthorizedInvoiceEgress;
using EcuNexo.Business.Inventory.Commands.ApproveInventoryDocument;
using EcuNexo.Business.Inventory.Commands.CreateInventoryDocument;
using EcuNexo.Business.Inventory.Commands.ReceiveInventoryTransfer;
using EcuNexo.Business.Inventory.Commands.SetStockMinimum;
using EcuNexo.Business.Inventory.Queries.GetInventoryDocument;
using EcuNexo.Business.Inventory.Queries.ListInventoryDocuments;
using EcuNexo.Business.Inventory.Queries.ListInventoryMovements;
using EcuNexo.Business.Inventory.Queries.ListStock;
using EcuNexo.Business.Repairs.Commands.CreateRepairDispatch;
using EcuNexo.Business.Repairs.Commands.DeleteRepairEquipmentPhoto;
using EcuNexo.Business.Repairs.Commands.LinkDispatchInvoice;
using EcuNexo.Business.Repairs.Commands.ImportRepairBatch;
using EcuNexo.Business.Repairs.Commands.UpdateEquipmentStatus;
using EcuNexo.Business.Repairs.Commands.UploadRepairEquipmentPhoto;
using EcuNexo.Business.Repairs.Excel;
using EcuNexo.Business.Repairs.Queries.GetDispatchInvoicePreview;
using EcuNexo.Business.Repairs.Queries.ListBatches;
using EcuNexo.Business.Repairs.Queries.VerifyDispatchPublic;
using EcuNexo.Business.Repairs.Storage;
using EcuNexo.Business.Repairs;
using EcuNexo.Business.Identity.Authorization;
using EcuNexo.Business.Identity.Commands;
using EcuNexo.Business.Identity.Commands.Login;
using EcuNexo.Business.Identity.PolicyEvaluation;
using EcuNexo.Business.Identity.Queries.EvaluateAuthorization;
using EcuNexo.Business.Identity.Queries.GetPermissionById;
using EcuNexo.Business.Identity.Queries.GetTenantRole;
using EcuNexo.Business.Identity.Queries.GetTenantUser;
using EcuNexo.Business.Identity.Queries.ListPermissionPolicies;
using EcuNexo.Business.Identity.Queries.ListPermissions;
using EcuNexo.Business.Identity.Queries.GetTenantDepartment;
using EcuNexo.Business.Identity.Queries.ListTenantDepartments;
using EcuNexo.Business.Identity.Queries.ListTenantRoles;
using EcuNexo.Business.Identity.Queries.ListTenantUsers;
using EcuNexo.Business.Platform.Navigation;
using EcuNexo.Business.Platform.Commands.UpsertUserUiPreferences;
using EcuNexo.Business.Platform.Queries.GetResolvedSettings;
using EcuNexo.Business.Platform.Queries.GetSession;
using EcuNexo.Business.Platform.Queries.GetSubscriptionSession;
using EcuNexo.Business.Platform.Queries.GetTenantMenu;
using EcuNexo.Business.Platform.Settings;
using EcuNexo.Business.Tenancy;
using EcuNexo.Business.Tenancy.Authorization;
using EcuNexo.Business.Tenancy.Commands;
using EcuNexo.Business.Tenancy.Commands.ActivateLicense;
using EcuNexo.Business.Tenancy.Commands.ApplySubscriptionLicenseUpgrade;
using EcuNexo.Business.Tenancy.Licensing;
using EcuNexo.Business.Tenancy.Commands.CancelSubscriptionCompany;
using EcuNexo.Business.Tenancy.Commands.ProvisionSubscriptionCompany;
using EcuNexo.Business.Tenancy.Commands.SwitchToCompanySession;
using EcuNexo.Business.Tenancy.Commands.UpdateSubscriptionCompany;
using EcuNexo.Business.Tenancy.Commands.UpdateTenantSriLegal;
using EcuNexo.Business.Tenancy.Commands.BrandLogos;
using EcuNexo.Business.Tenancy.Queries.BrandLogos;
using EcuNexo.Business.Tenancy.Queries.GetOnboardingStatus;
using EcuNexo.Business.Tenancy.Queries.GetSubscriptionCompany;
using EcuNexo.Business.Tenancy.Queries.GetTenantById;
using EcuNexo.Business.Tenancy.Queries.ListSubscriptionCompanies;
using EcuNexo.Business.Warehousing;
using EcuNexo.Business.Warehousing.Commands.CreateWarehouse;
using EcuNexo.Business.Warehousing.Commands.UpdateWarehouse;
using EcuNexo.Business.Warehousing.Queries.GetWarehouse;
using EcuNexo.Business.Warehousing.Queries.ListWarehouses;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

namespace EcuNexo.Business;

public static class DependencyInjection
{
    public static IServiceCollection AddBusiness(this IServiceCollection services, IConfiguration? configuration = null)
    {
        var storageOptions = configuration?.GetSection(StorageOptions.SectionName).Get<StorageOptions>() ?? new StorageOptions();
        services.AddSingleton(storageOptions);
        services.AddSingleton<IStorageService, BackblazeB2StorageService>();
        services.AddSingleton<IImageProcessingService, ImageProcessingService>();

        services.AddValidatorsFromAssemblyContaining<CreateTenantValidator>();

        services.AddScoped<ICommandHandler<CreateTenantCommand, CreateTenantResponse>, CreateTenantHandler>();
        services.AddScoped<ICommandHandler<OnboardTenantWithActivationCommand, OnboardTenantWithActivationResponse>, OnboardTenantWithActivationHandler>();
        services.AddScoped<ICommandHandler<ActivateLicenseCommand, ActivateLicenseResponse>, ActivateLicenseHandler>();
        services.AddScoped<ICommandHandler<ApplySubscriptionLicenseUpgradeCommand, ApplySubscriptionLicenseUpgradeResponse>, ApplySubscriptionLicenseUpgradeHandler>();
        services.AddScoped<ICommandHandler<ProvisionSubscriptionCompanyCommand, ProvisionSubscriptionCompanyResponse>, ProvisionSubscriptionCompanyHandler>();
        services.AddScoped<ICommandHandler<CancelSubscriptionCompanyCommand, CancelSubscriptionCompanyResponse>, CancelSubscriptionCompanyHandler>();
        services.AddScoped<ICommandHandler<UpdateSubscriptionCompanyCommand, UpdateSubscriptionCompanyResponse>, UpdateSubscriptionCompanyHandler>();
        services.AddScoped<ICommandHandler<SwitchToCompanySessionCommand, SwitchToCompanySessionResponse>, SwitchToCompanySessionHandler>();
        services.AddScoped<ICommandHandler<UpdateTenantSriLegalCommand, UpdateTenantSriLegalResponse>, UpdateTenantSriLegalHandler>();
        services.AddScoped<ICommandHandler<UploadTenantBrandLogoCommand, UploadTenantBrandLogoResponse>, UploadTenantBrandLogoHandler>();
        services.AddScoped<ICommandHandler<SelectTenantBrandLogosCommand, SelectTenantBrandLogosResponse>, SelectTenantBrandLogosHandler>();
        services.AddScoped<ICommandHandler<DeleteTenantBrandLogoCommand, DeleteTenantBrandLogoResponse>, DeleteTenantBrandLogoHandler>();
        services.AddScoped<ICommandHandler<CreateUserCommand, CreateUserResponse>, CreateUserHandler>();
        services.AddScoped<ICommandHandler<UpdateUserCommand, UpdateUserResponse>, UpdateUserHandler>();
        services.AddScoped<ICommandHandler<SetUserDisabledCommand, SetUserDisabledResponse>, SetUserDisabledHandler>();
        services.AddScoped<ICommandHandler<SetUserPasswordCommand, SetUserPasswordResponse>, SetUserPasswordHandler>();
        services.AddScoped<ICommandHandler<SendUserPasswordResetEmailCommand, SendUserPasswordResetEmailResponse>, SendUserPasswordResetEmailHandler>();
        services.AddScoped<ICommandHandler<SoftDeleteUserCommand, SoftDeleteUserResponse>, SoftDeleteUserHandler>();
        services.AddScoped<ICommandHandler<CreateRoleCommand, CreateRoleResponse>, CreateRoleHandler>();
        services.AddScoped<ICommandHandler<UpdateRoleCommand, UpdateRoleResponse>, UpdateRoleHandler>();
        services.AddScoped<ICommandHandler<DeleteRoleCommand, DeleteRoleResponse>, DeleteRoleHandler>();
        services.AddScoped<ICommandHandler<CreateDepartmentCommand, CreateDepartmentResponse>, CreateDepartmentHandler>();
        services.AddScoped<ICommandHandler<UpdateDepartmentCommand, UpdateDepartmentResponse>, UpdateDepartmentHandler>();
        services.AddScoped<ICommandHandler<DeleteDepartmentCommand, DeleteDepartmentResponse>, DeleteDepartmentHandler>();
        services.AddScoped<ICommandHandler<CreateCategoryCommand, CreateCategoryResponse>, CreateCategoryHandler>();
        services.AddScoped<ICommandHandler<UpdateCategoryCommand, UpdateCategoryResponse>, UpdateCategoryHandler>();
        services.AddScoped<ICommandHandler<SoftDeleteCategoryCommand, SoftDeleteCategoryResponse>, SoftDeleteCategoryHandler>();
        services.AddScoped<ICommandHandler<CreateCatalogItemCommand, CreateCatalogItemResponse>, CreateCatalogItemHandler>();
        services.AddScoped<ICommandHandler<UpdateCatalogItemCommand, UpdateCatalogItemResponse>, UpdateCatalogItemHandler>();
        services.AddScoped<ICommandHandler<SoftDeleteCatalogItemCommand, SoftDeleteCatalogItemResponse>, SoftDeleteCatalogItemHandler>();
        services.AddScoped<ICommandHandler<CreateWarehouseCommand, CreateWarehouseResponse>, CreateWarehouseHandler>();
        services.AddScoped<ICommandHandler<UpdateWarehouseCommand, UpdateWarehouseResponse>, UpdateWarehouseHandler>();
        services.AddScoped<ICommandHandler<CreateInventoryDocumentCommand, CreateInventoryDocumentResponse>, CreateInventoryDocumentHandler>();
        services.AddScoped<ICommandHandler<ApproveInventoryDocumentCommand, ApproveInventoryDocumentResponse>, ApproveInventoryDocumentHandler>();
        services.AddScoped<ICommandHandler<ReceiveInventoryTransferCommand, ReceiveInventoryTransferResponse>, ReceiveInventoryTransferHandler>();
        services.AddScoped<ICommandHandler<SetStockMinimumCommand, SetStockMinimumResponse>, SetStockMinimumHandler>();
        services.AddScoped<ICommandHandler<ApplyAuthorizedInvoiceEgressCommand, ApplyAuthorizedInvoiceEgressResponse>, ApplyAuthorizedInvoiceEgressHandler>();
        services.AddScoped<ICommandHandler<AssignUserRoleCommand, AssignUserRoleResponse>, AssignUserRoleHandler>();
        services.AddScoped<ICommandHandler<UnassignUserRoleCommand, UnassignUserRoleResponse>, UnassignUserRoleHandler>();
        services.AddScoped<ICommandHandler<CreatePermissionCommand, CreatePermissionResponse>, CreatePermissionHandler>();
        services.AddScoped<ICommandHandler<GrantRolePermissionCommand, GrantRolePermissionResponse>, GrantRolePermissionHandler>();
        services.AddScoped<ICommandHandler<UnassignRolePermissionCommand, UnassignRolePermissionResponse>, UnassignRolePermissionHandler>();
        services.AddScoped<ICommandHandler<ReplaceRolePermissionsCommand, ReplaceRolePermissionsResponse>, ReplaceRolePermissionsHandler>();
        services.AddScoped<ICommandHandler<CreatePolicyCommand, CreatePolicyResponse>, CreatePolicyHandler>();
        services.AddScoped<ICommandHandler<LoginCommand, LoginResponse>, LoginHandler>();
        services.AddScoped<ICommandHandler<UpsertUserUiPreferencesCommand, UpsertUserUiPreferencesResponse>, UpsertUserUiPreferencesHandler>();

        services.AddScoped<ILicenseComplianceService, LicenseComplianceService>();
        services.AddScoped<IModuleUsageTracker, ModuleUsageTracker>();

        services.AddScoped<IQueryHandler<GetOnboardingStatusQuery, OnboardingStatusResponse>, GetOnboardingStatusHandler>();
        services.AddScoped<IQueryHandler<GetTenantByIdQuery, GetTenantByIdResponse>, GetTenantByIdHandler>();
        services.AddScoped<IQueryHandler<ListTenantBrandLogosQuery, TenantBrandLogoCatalogResponse>, ListTenantBrandLogosHandler>();
        services.AddScoped<IQueryHandler<GetTenantBrandLogoFileQuery, TenantBrandLogoFileResponse>, GetTenantBrandLogoFileHandler>();
        services.AddScoped<IQueryHandler<ListSubscriptionCompaniesQuery, ListSubscriptionCompaniesResponse>, ListSubscriptionCompaniesHandler>();
        services.AddScoped<IQueryHandler<GetSubscriptionCompanyQuery, GetTenantByIdResponse>, GetSubscriptionCompanyHandler>();
        services.AddScoped<IQueryHandler<ListTenantUsersQuery, IReadOnlyList<UserListItemResponse>>, ListTenantUsersHandler>();
        services.AddScoped<IQueryHandler<GetTenantUserQuery, GetTenantUserResponse>, GetTenantUserHandler>();
        services.AddScoped<IQueryHandler<ListTenantRolesQuery, IReadOnlyList<RoleListItemResponse>>, ListTenantRolesHandler>();
        services.AddScoped<IQueryHandler<ListTenantDepartmentsQuery, IReadOnlyList<DepartmentListItemResponse>>, ListTenantDepartmentsHandler>();
        services.AddScoped<IQueryHandler<GetTenantDepartmentQuery, DepartmentListItemResponse>, GetTenantDepartmentHandler>();
        services.AddScoped<IQueryHandler<ListCategoriesQuery, IReadOnlyList<CategoryListItemResponse>>, ListCategoriesHandler>();
        services.AddScoped<IQueryHandler<ListCatalogItemsQuery, IReadOnlyList<CatalogItemListItemResponse>>, ListCatalogItemsHandler>();
        services.AddScoped<IQueryHandler<GetCatalogItemQuery, CatalogItemDetailResponse>, GetCatalogItemHandler>();
        services.AddScoped<IQueryHandler<ListWarehousesQuery, IReadOnlyList<WarehouseListItemResponse>>, ListWarehousesHandler>();
        services.AddScoped<IQueryHandler<GetWarehouseQuery, WarehouseDetailResponse>, GetWarehouseHandler>();
        services.AddScoped<IQueryHandler<ListStockQuery, IReadOnlyList<StockListItemResponse>>, ListStockHandler>();
        services.AddScoped<IQueryHandler<ListInventoryDocumentsQuery, IReadOnlyList<InventoryDocumentListItemResponse>>, ListInventoryDocumentsHandler>();
        services.AddScoped<IQueryHandler<GetInventoryDocumentQuery, InventoryDocumentDetailResponse>, GetInventoryDocumentHandler>();
        services.AddScoped<IQueryHandler<ListInventoryMovementsQuery, IReadOnlyList<InventoryMovementListItemResponse>>, ListInventoryMovementsHandler>();
        services.AddScoped<IQueryHandler<GetTenantRoleQuery, GetTenantRoleResponse>, GetTenantRoleHandler>();
        services.AddScoped<IQueryHandler<ListPermissionsQuery, IReadOnlyList<PermissionListItemResponse>>, ListPermissionsHandler>();
        services.AddScoped<IQueryHandler<GetPermissionByIdQuery, PermissionDetailResponse>, GetPermissionByIdHandler>();
        services.AddScoped<IQueryHandler<ListPermissionPoliciesQuery, IReadOnlyList<PolicyListItemResponse>>, ListPermissionPoliciesHandler>();
        services.AddScoped<IQueryHandler<GetSessionQuery, SessionResponse>, GetSessionHandler>();
        services.AddScoped<IQueryHandler<GetResolvedSettingsQuery, GetResolvedSettingsResponse>, GetResolvedSettingsHandler>();
        services.AddScoped<IQueryHandler<GetSubscriptionSessionQuery, SubscriptionSessionResponse>, GetSubscriptionSessionHandler>();
        services.AddScoped<IQueryHandler<GetTenantMenuQuery, TenantMenuResponse>, GetTenantMenuHandler>();
        services.AddScoped<IQueryHandler<EvaluateAuthorizationQuery, EvaluateAuthorizationResponse>, EvaluateAuthorizationHandler>();

        services.AddScoped<IPolicyEvaluator, DynamicExpressoPolicyEvaluator>();
        services.AddScoped<IModuleEntitlementGuard, ModuleEntitlementGuard>();
        services.AddScoped<IPermissionAccessGuard, PermissionAccessGuard>();
        services.AddScoped<ICompanyOwnerGuard, CompanyOwnerGuard>();
        services.AddScoped<IUiAccessEvaluator, UiAccessEvaluator>();
        services.AddScoped<ISettingsResolver, SettingsResolver>();
        services.AddSingleton<EmbeddedNavigationBuilder>();
        services.AddSingleton<INavigationBuilder>(sp => sp.GetRequiredService<EmbeddedNavigationBuilder>());
        services.AddScoped<IMenuNavigationBuilder, MenuNavigationBuilder>();

        services.AddScoped<ISender, Sender>();
        services.AddScoped<DefaultWarehouseProvisioner>();
        services.AddScoped<InventoryDocumentApprovalService>();

        // Repairs (Taller B2B)
        services.AddScoped<IRepairBatchExcelService, RepairBatchExcelService>();
        services.AddScoped<IAwsS3StorageService, AwsS3StorageService>();

        services.AddScoped<ICommandHandler<ImportRepairBatchCommand, ImportRepairBatchResponse>, ImportRepairBatchHandler>();
        services.AddScoped<ICommandHandler<UpdateEquipmentStatusCommand, UpdateEquipmentStatusResponse>, UpdateEquipmentStatusHandler>();
        services.AddScoped<ICommandHandler<UploadRepairEquipmentPhotoCommand, RepairEquipmentPhotoResponse>, UploadRepairEquipmentPhotoHandler>();
        services.AddScoped<ICommandHandler<DeleteRepairEquipmentPhotoCommand, DeleteRepairEquipmentPhotoResponse>, DeleteRepairEquipmentPhotoHandler>();
        services.AddScoped<ICommandHandler<CreateRepairDispatchCommand, CreateRepairDispatchResponse>, CreateRepairDispatchHandler>();
        services.AddScoped<ICommandHandler<LinkDispatchInvoiceCommand, LinkDispatchInvoiceResponse>, LinkDispatchInvoiceHandler>();
        services.AddScoped<IQueryHandler<ListBatchesQuery, IReadOnlyList<BatchListItemResponse>>, ListBatchesHandler>();
        services.AddScoped<IQueryHandler<VerifyDispatchPublicQuery, PublicDispatchVerificationResponse>, VerifyDispatchPublicHandler>();
        services.AddScoped<IQueryHandler<GetDispatchInvoicePreviewQuery, DispatchInvoicePreviewResponse>, GetDispatchInvoicePreviewHandler>();
        services.AddScoped<RepairCatalogServiceEnsurer>();

        // Catalog Item Images (E-commerce / Optimización)
        services.AddScoped<ICommandHandler<UploadCatalogItemImageCommand, CatalogItemImageResponse>, UploadCatalogItemImageHandler>();
        services.AddScoped<ICommandHandler<DeleteCatalogItemImageCommand, DeleteCatalogItemImageResponse>, DeleteCatalogItemImageHandler>();
        services.AddScoped<ICommandHandler<SetCatalogItemMainImageCommand, SetCatalogItemMainImageResponse>, SetCatalogItemMainImageHandler>();
        services.AddScoped<ICommandHandler<ReorderCatalogItemImagesCommand, ReorderCatalogItemImagesResponse>, ReorderCatalogItemImagesHandler>();
        services.AddScoped<ICommandHandler<UpdateCatalogItemImageAltTextCommand, UpdateCatalogItemImageAltTextResponse>, UpdateCatalogItemImageAltTextHandler>();

        return services;
    }
}
