// <auto-generated />
using System;
using EcuNexo.Business.Abstractions;

#nullable disable
#pragma warning disable IDE0005

namespace EcuNexo.Business.Platform.Queries.GetDashboardAnalytics;

public sealed record GetDashboardAnalyticsQuery(Guid TenantId) : IQuery<DashboardAnalyticsDto>;
