// <auto-generated />
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EcuNexo.Business.Abstractions;
using EcuNexo.Business.Accounting.Repositories;
using EcuNexo.Business.Customers.Repositories;
using EcuNexo.Business.Ecommerce.Repositories;
using EcuNexo.Business.Inventory;
using EcuNexo.Business.Purchases.Repositories;
using EcuNexo.Business.RemisionGuides;
using EcuNexo.Business.Repairs.Repositories;
using EcuNexo.Business.Warehousing;
using EcuNexo.Core.Accounting;
using EcuNexo.Core.Common;
using EcuNexo.Core.Customers;
using EcuNexo.Core.Ecommerce;
using EcuNexo.Core.Purchases;
using EcuNexo.Core.RemisionGuides;
using EcuNexo.Core.Repairs;
using EcuNexo.Core.Warehousing;

#nullable disable
#pragma warning disable IDE0005

namespace EcuNexo.Business.Platform.Queries.GetDashboardAnalytics;

public sealed class GetDashboardAnalyticsHandler
    : IQueryHandler<GetDashboardAnalyticsQuery, DashboardAnalyticsDto>
{
    private readonly ICustomerRepository _customers;
    private readonly IStockRepository _stocks;
    private readonly IWarehouseRepository _warehouses;
    private readonly IRemisionGuideRepository _remisionGuides;
    private readonly IRepairEquipmentRepository _repairs;
    private readonly IPurchaseRepository _purchases;
    private readonly IRepairBatchRepository _repairBatches;
    private readonly IEcommerceOrderRepository _ecommerceOrders;
    private readonly IExpenseTypeRepository _expenseTypes;
    private readonly IJournalEntryRepository _journalEntries;
    private readonly IAccountRepository _accounts;

    public GetDashboardAnalyticsHandler(
        ICustomerRepository customers,
        IStockRepository stocks,
        IWarehouseRepository warehouses,
        IRemisionGuideRepository remisionGuides,
        IRepairEquipmentRepository repairs,
        IPurchaseRepository purchases,
        IRepairBatchRepository repairBatches,
        IEcommerceOrderRepository ecommerceOrders,
        IExpenseTypeRepository expenseTypes,
        IJournalEntryRepository journalEntries,
        IAccountRepository accounts)
    {
        _customers = customers;
        _stocks = stocks;
        _warehouses = warehouses;
        _remisionGuides = remisionGuides;
        _repairs = repairs;
        _purchases = purchases;
        _repairBatches = repairBatches;
        _ecommerceOrders = ecommerceOrders;
        _expenseTypes = expenseTypes;
        _journalEntries = journalEntries;
        _accounts = accounts;
    }

    public async Task<Result<DashboardAnalyticsDto>> Handle(
        GetDashboardAnalyticsQuery query,
        CancellationToken ct)
    {
        var tenantId = query.TenantId;

        // 1. Clientes por tipo de categoría (Cómputo dinámico desde la BD PostgreSQL)
        var customerList = await _customers.ListByTenantAsync(tenantId, ct).ConfigureAwait(false);
        var customerTypeDistribution = BuildCustomerTypeDistribution(customerList);

        // 2. Stock por Bodega (Cómputo dinámico desde BD)
        var warehouseList = await _warehouses.ListActiveByTenantAsync(tenantId, ct).ConfigureAwait(false);
        var warehouseStockDistribution = await BuildWarehouseStockDistributionAsync(tenantId, warehouseList, ct).ConfigureAwait(false);

        // 3. Guías de Remisión SRI (Tipo 06) (Cómputo dinámico desde BD)
        var remisionList = await _remisionGuides.ListAsync(tenantId, null, null, null, null, ct).ConfigureAwait(false);
        var remisionStatusDistribution = BuildRemisionStatusDistribution(remisionList);

        // 4. Taller de Reparaciones (Cómputo dinámico desde BD si se inyectó repo de lotes)
        var repairStagesDistribution = await BuildRepairStagesDistributionAsync(tenantId, ct).ConfigureAwait(false);

        // 5. Ventas y Comprobantes SRI (Cómputo dinámico desde órdenes ecommerce y comprobantes)
        var salesTrend = await BuildSalesMonthlyTrendAsync(tenantId, ct).ConfigureAwait(false);
        var sriStatus = BuildSriStatusDistribution(remisionList);

        // 6. Compras y Gastos (Cómputo dinámico desde la BD)
        var purchasesExpenses = await BuildPurchasesExpensesTrendAsync(tenantId, ct).ConfigureAwait(false);

        // 7. Balances Financieros NIIF (Cómputo dinámico desde asientos contables)
        var financialBalance = await BuildFinancialBalanceAsync(tenantId, ct).ConfigureAwait(false);

        // 8. Declaraciones Tributarias F104 (Cómputo dinámico IVA/Retenciones)
        var taxDeclarations = BuildTaxDeclarationsTrend(salesTrend, purchasesExpenses);

        var result = new DashboardAnalyticsDto(
            salesTrend,
            sriStatus,
            customerTypeDistribution,
            purchasesExpenses,
            warehouseStockDistribution,
            remisionStatusDistribution,
            repairStagesDistribution,
            financialBalance,
            taxDeclarations);

        return Result.Success(result);
    }

    private static List<CustomerTypeDistributionDto> BuildCustomerTypeDistribution(IReadOnlyList<Customer> customers)
    {
        if (customers == null || customers.Count == 0)
        {
            return new List<CustomerTypeDistributionDto>
            {
                new("Corporativo B2B", 0),
                new("Persona Natural", 0),
                new("Mayoristas", 0),
                new("Consumidor Final", 0)
            };
        }

        var b2b = customers.Count(c => c.CustomerType == CustomerType.CorporativoB2B);
        var natural = customers.Count(c => c.CustomerType == CustomerType.PersonaNatural);
        var mayorista = customers.Count(c => c.CustomerType == CustomerType.DistribuidorMayorista);
        var final = Math.Max(0, customers.Count - (b2b + natural + mayorista));

        return new List<CustomerTypeDistributionDto>
        {
            new("Corporativo B2B", b2b),
            new("Persona Natural", natural),
            new("Mayoristas", mayorista),
            new("Consumidor Final", final)
        };
    }

    private async Task<List<WarehouseStockDistributionDto>> BuildWarehouseStockDistributionAsync(
        Guid tenantId,
        IReadOnlyList<Warehouse> warehouses,
        CancellationToken ct)
    {
        var result = new List<WarehouseStockDistributionDto>();
        if (warehouses != null && warehouses.Count > 0)
        {
            foreach (var w in warehouses.Take(6))
            {
                var stockItems = await _stocks.ListByTenantAsync(tenantId, w.Id, ct).ConfigureAwait(false);
                var totalStock = stockItems != null ? (int)stockItems.Sum(s => s.Quantity) : 0;
                var minThreshold = stockItems != null ? (int)stockItems.Sum(s => s.MinimumQuantity ?? 0m) : 0;
                result.Add(new WarehouseStockDistributionDto(w.Name, totalStock, minThreshold));
            }
        }

        if (result.Count == 0)
        {
            result.Add(new WarehouseStockDistributionDto("Matriz Principal", 0, 0));
            result.Add(new WarehouseStockDistributionDto("Sucursal Norte", 0, 0));
            result.Add(new WarehouseStockDistributionDto("Bodega Cumbayá", 0, 0));
            result.Add(new WarehouseStockDistributionDto("Taller Guayaquil", 0, 0));
        }

        return result;
    }

    private static List<StatusDistributionDto> BuildRemisionStatusDistribution(IReadOnlyList<RemisionGuide> remisiones)
    {
        if (remisiones == null || remisiones.Count == 0)
        {
            return new List<StatusDistributionDto>
            {
                new("Autorizadas", 0, "#10b981"),
                new("En Tránsito", 0, "#0284c7"),
                new("Entregadas", 0, "#6366f1")
            };
        }

        return new List<StatusDistributionDto>
        {
            new("Autorizadas", remisiones.Count(g => g.Status == RemisionGuideStatus.Authorized), "#10b981"),
            new("En Tránsito", remisiones.Count(g => g.Status == RemisionGuideStatus.InTransit), "#0284c7"),
            new("Entregadas", remisiones.Count(g => g.Status == RemisionGuideStatus.Delivered), "#6366f1")
        };
    }

    private async Task<List<StatusDistributionDto>> BuildRepairStagesDistributionAsync(Guid tenantId, CancellationToken ct)
    {
        if (_repairBatches != null)
        {
            var batches = await _repairBatches.ListByTenantAsync(tenantId, null, null, ct).ConfigureAwait(false);
            if (batches != null && batches.Count > 0)
            {
                var received = batches.Sum(b => b.ReceivedCount);
                var inRepair = batches.Sum(b => b.InRepairCount);
                var readyOrDispatched = batches.Sum(b => b.ReadyCount + b.DispatchedCount);
                return new List<StatusDistributionDto>
                {
                    new("Diagnóstico", received, "#8b5cf6"),
                    new("Reparación", inRepair, "#eab308"),
                    new("QC / Despacho", readyOrDispatched, "#10b981")
                };
            }
        }

        return new List<StatusDistributionDto>
        {
            new("Diagnóstico", 0, "#8b5cf6"),
            new("Reparación", 0, "#eab308"),
            new("QC / Despacho", 0, "#10b981")
        };
    }

    private async Task<List<SalesMonthlyTrendDto>> BuildSalesMonthlyTrendAsync(Guid tenantId, CancellationToken ct)
    {
        var months = GetLast6MonthsLabels();
        var result = new List<SalesMonthlyTrendDto>();

        if (_ecommerceOrders != null)
        {
            var pagedOrders = await _ecommerceOrders.ListAsync(tenantId, null, null, null, null, null, 1, 1000, ct).ConfigureAwait(false);
            var orders = pagedOrders.Items;

            if (orders != null && orders.Count > 0)
            {
                foreach (var (monthName, monthIndex, year) in months)
                {
                    var monthlyOrders = orders.Where(o => o.OrderDate.Month == monthIndex && o.OrderDate.Year == year).ToList();
                    var totalSales = monthlyOrders.Sum(o => o.TotalAmount);
                    var count = monthlyOrders.Count;
                    result.Add(new SalesMonthlyTrendDto(monthName, totalSales, count));
                }
                return result;
            }
        }

        foreach (var (monthName, _, _) in months)
        {
            result.Add(new SalesMonthlyTrendDto(monthName, 0m, 0));
        }

        return result;
    }

    private static List<StatusDistributionDto> BuildSriStatusDistribution(IReadOnlyList<RemisionGuide> remisiones)
    {
        if (remisiones == null || remisiones.Count == 0)
        {
            return new List<StatusDistributionDto>
            {
                new("Autorizadas", 0, "#10b981"),
                new("Borradores", 0, "#6366f1"),
                new("Devueltas", 0, "#f59e0b")
            };
        }

        var auth = remisiones.Count(r => r.Status == RemisionGuideStatus.Authorized);
        var draft = remisiones.Count(r => r.Status == RemisionGuideStatus.Draft);
        var returned = remisiones.Count(r => r.Status == RemisionGuideStatus.Cancelled);

        return new List<StatusDistributionDto>
        {
            new("Autorizadas", auth, "#10b981"),
            new("Borradores", draft, "#6366f1"),
            new("Devueltas", returned, "#f59e0b")
        };
    }

    private async Task<List<PurchasesExpensesTrendDto>> BuildPurchasesExpensesTrendAsync(Guid tenantId, CancellationToken ct)
    {
        var months = GetLast6MonthsLabels();
        var result = new List<PurchasesExpensesTrendDto>();

        if (_purchases != null)
        {
            var purchases = await _purchases.ListAsync(tenantId, null, null, null, null, null, null, ct).ConfigureAwait(false);
            if (purchases != null && purchases.Count > 0)
            {
                foreach (var (monthName, monthIndex, year) in months)
                {
                    var monthlyPurchases = purchases.Where(p => p.IssueDate.Month == monthIndex && p.IssueDate.Year == year).ToList();
                    var totalPurchases = monthlyPurchases.Where(p => p.ExpenseTypeId == null).Sum(p => p.TotalAmount);
                    var totalExpenses = monthlyPurchases.Where(p => p.ExpenseTypeId != null).Sum(p => p.TotalAmount);
                    result.Add(new PurchasesExpensesTrendDto(monthName, totalPurchases, totalExpenses));
                }
                return result;
            }
        }

        foreach (var (monthName, _, _) in months)
        {
            result.Add(new PurchasesExpensesTrendDto(monthName, 0m, 0m));
        }

        return result;
    }

    private async Task<List<FinancialBalanceDto>> BuildFinancialBalanceAsync(Guid tenantId, CancellationToken ct)
    {
        if (_journalEntries != null && _accounts != null)
        {
            var entries = await _journalEntries.ListAsync(tenantId, null, null, null, null, null, ct).ConfigureAwait(false);
            if (entries != null && entries.Count > 0)
            {
                var accounts = await _accounts.ListAsync(tenantId, null, null, true, null, ct).ConfigureAwait(false);
                var assetAccountIds = accounts.Where(a => a.AccountType == AccountType.Asset).Select(a => a.Id).ToHashSet();
                var liabilityAccountIds = accounts.Where(a => a.AccountType == AccountType.Liability).Select(a => a.Id).ToHashSet();
                var equityAccountIds = accounts.Where(a => a.AccountType == AccountType.Equity).Select(a => a.Id).ToHashSet();

                var lines = entries.SelectMany(e => e.Lines).ToList();
                var activos = lines.Where(l => assetAccountIds.Contains(l.AccountId)).Sum(l => l.Debit - l.Credit);
                var pasivos = lines.Where(l => liabilityAccountIds.Contains(l.AccountId)).Sum(l => l.Credit - l.Debit);
                var patrimonio = lines.Where(l => equityAccountIds.Contains(l.AccountId)).Sum(l => l.Credit - l.Debit);

                return new List<FinancialBalanceDto>
                {
                    new("Activos", Math.Max(0m, activos)),
                    new("Pasivos", Math.Max(0m, pasivos)),
                    new("Patrimonio", Math.Max(0m, patrimonio))
                };
            }
        }

        return new List<FinancialBalanceDto>
        {
            new("Activos", 0m),
            new("Pasivos", 0m),
            new("Patrimonio", 0m)
        };
    }

    private static List<TaxDeclarationTrendDto> BuildTaxDeclarationsTrend(
        List<SalesMonthlyTrendDto> sales,
        List<PurchasesExpensesTrendDto> purchases)
    {
        var result = new List<TaxDeclarationTrendDto>();
        for (var i = 0; i < sales.Count; i++)
        {
            var month = sales[i].Mes;
            var vatCharged = Math.Round(sales[i].Ventas * 0.15m, 2);
            var vatPaid = Math.Round((purchases[i].Inventario + purchases[i].Servicios) * 0.15m, 2);
            var withholding = Math.Round(vatCharged * 0.20m, 2);
            result.Add(new TaxDeclarationTrendDto(month, vatCharged, vatPaid, withholding));
        }
        return result;
    }

    private static List<(string MonthName, int MonthIndex, int Year)> GetLast6MonthsLabels()
    {
        var result = new List<(string, int, int)>();
        var now = DateTime.UtcNow;
        var culture = new CultureInfo("es-EC");

        for (var i = 5; i >= 0; i--)
        {
            var date = now.AddMonths(-i);
            var monthName = culture.DateTimeFormat.GetAbbreviatedMonthName(date.Month);
            monthName = char.ToUpper(monthName[0]) + monthName[1..].TrimEnd('.');
            result.Add((monthName, date.Month, date.Year));
        }

        return result;
    }
}
