import { StyleSheet } from '@react-pdf/renderer'
import type { RidePalette } from '@/pages/facturacion/rideFacturaPalette'

export function createRideStyles(p: RidePalette) {
  const card = {
    borderWidth: 1,
    borderColor: p.hairline,
    borderRadius: 6,
    overflow: 'hidden' as const,
    backgroundColor: p.surface,
  }

  return StyleSheet.create({
    page: {
      paddingTop: 0,
      paddingBottom: 48,
      paddingHorizontal: 0,
      fontSize: 9.2,
      fontFamily: 'Helvetica',
      color: p.ink,
      backgroundColor: p.paper,
    },
    topBar: { height: 3, backgroundColor: p.accent },
    body: { paddingTop: 16, paddingBottom: 8, paddingHorizontal: 22 },
    headerRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' },
    leftBox: { flex: 1.18 },
    brandStack: { marginBottom: 12 },
    logoSlot: {
      width: '100%',
      height: 52,
      marginBottom: 8,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    logoImage: {
      width: '100%',
      height: 52,
      objectFit: 'contain',
      objectPosition: 'left',
    },
    logoWatermark: {
      fontSize: 11,
      fontFamily: 'Helvetica-Bold',
      color: p.accent,
      opacity: 0.35,
      letterSpacing: 2,
      textAlign: 'left',
    },
    brandText: { width: '100%' },
    companyName: {
      fontSize: 13.5,
      fontFamily: 'Helvetica-Bold',
      color: p.ink,
      marginBottom: 3,
    },
    companyRuc: { fontSize: 9, color: p.muted, letterSpacing: 0.3 },
    metaField: { marginBottom: 5 },
    metaLabel: {
      fontSize: 7,
      fontFamily: 'Helvetica-Bold',
      color: p.muted,
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      marginBottom: 1.5,
    },
    metaValue: { fontSize: 9.4, color: p.ink },
    rimpe: {
      marginTop: 6,
      fontSize: 8,
      fontFamily: 'Helvetica-Bold',
      color: p.accent,
      letterSpacing: 0.6,
    },
    rightBox: { flex: 0.92, minWidth: 0, ...card },
    accentStrip: { height: 3, backgroundColor: p.accent },
    rightBand: {
      backgroundColor: p.headerFill,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderBottomWidth: 1,
      borderBottomColor: p.hairline,
    },
    facturaTitle: {
      fontSize: 15,
      fontFamily: 'Helvetica-Bold',
      color: p.accent,
      textAlign: 'center',
      letterSpacing: 2.8,
    },
    docNumber: {
      textAlign: 'center',
      marginTop: 4,
      fontSize: 10.5,
      color: p.ink,
    },
    rightBody: { paddingVertical: 11, paddingHorizontal: 10 },
    authValue: { fontSize: 8.2, color: p.ink, maxWidth: '100%' },
    barcodeWrap: { marginTop: 8, alignItems: 'center' },
    barcode: { width: 210, height: 36, marginBottom: 3 },
    claveText: { fontSize: 7.2, textAlign: 'center', color: p.muted },
    buyerBox: { marginTop: 12, paddingVertical: 10, paddingHorizontal: 12, ...card },
    buyerGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    buyerCell: { width: '50%', marginBottom: 8, paddingRight: 10 },
    buyerCellFull: { width: '100%', marginBottom: 8 },
    tableBox: { marginTop: 12, ...card },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: p.headerFill,
      paddingVertical: 7,
      fontFamily: 'Helvetica-Bold',
      fontSize: 7.6,
      color: p.ink,
      borderBottomWidth: 1,
      borderBottomColor: p.hairline,
    },
    tableRow: {
      flexDirection: 'row',
      borderTopWidth: 0.4,
      borderColor: p.hairline,
      paddingVertical: 6,
      fontSize: 8.6,
    },
    tableRowAlt: { backgroundColor: p.zebra },
    colCod: { width: '13%', paddingHorizontal: 5 },
    colCant: { width: '11%', paddingHorizontal: 5, textAlign: 'right' },
    colDesc: { width: '30%', paddingHorizontal: 5 },
    colDet: { width: '14%', paddingHorizontal: 5 },
    colPUnit: { width: '12%', paddingHorizontal: 5, textAlign: 'right' },
    colDisc: { width: '10%', paddingHorizontal: 5, textAlign: 'right' },
    colTotal: { width: '10%', paddingHorizontal: 5, textAlign: 'right' },
    bottomRow: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 12,
      alignItems: 'flex-start',
    },
    leftCol: { flex: 0.95 },
    sectionBar: {
      backgroundColor: p.headerFill,
      color: p.ink,
      paddingVertical: 5,
      paddingHorizontal: 8,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      borderBottomWidth: 1,
      borderBottomColor: p.hairline,
    },
    infoBox: { marginBottom: 10, ...card },
    infoBody: { padding: 8 },
    payBox: { ...card },
    payHeader: {
      flexDirection: 'row',
      backgroundColor: p.headerFill,
      color: p.ink,
      paddingVertical: 5,
      paddingHorizontal: 8,
      fontFamily: 'Helvetica-Bold',
      fontSize: 8,
      letterSpacing: 0.8,
    },
    payRow: {
      flexDirection: 'row',
      paddingVertical: 7,
      paddingHorizontal: 8,
    },
    payForma: { flex: 1 },
    payValor: { width: 56, textAlign: 'right', fontFamily: 'Helvetica-Bold' },
    payPlazo: { width: 50, textAlign: 'right', color: p.muted },
    totalsBox: { flex: 1.05, ...card },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 4,
      paddingHorizontal: 8,
      borderBottomWidth: 0.4,
      borderColor: p.hairline,
    },
    totalLabel: { color: p.muted, fontSize: 8.4 },
    totalValue: { color: p.ink },
    totalStrong: { backgroundColor: p.accentSoft, borderBottomWidth: 0 },
    totalStrongText: {
      color: p.accentDeep,
      fontFamily: 'Helvetica-Bold',
      fontSize: 10,
    },
    thanksBox: { marginTop: 16, alignItems: 'center', paddingHorizontal: 16 },
    thanksRule: { width: 36, height: 1.5, backgroundColor: p.accent, marginBottom: 8 },
    thanksTitle: {
      fontFamily: 'Helvetica-Bold',
      textAlign: 'center',
      marginBottom: 6,
      fontSize: 8,
      letterSpacing: 2.2,
      color: p.muted,
    },
    thanksLine: { marginBottom: 2.5, fontSize: 9, textAlign: 'center', color: p.ink },
    infoRow: { marginBottom: 6 },
    softwareFooter: {
      position: 'absolute',
      bottom: 14,
      left: 22,
      right: 22,
      paddingTop: 8,
      borderTopWidth: 0.6,
      borderColor: p.hairline,
      alignItems: 'center',
    },
    softwareFooterLine: {
      fontSize: 7.6,
      color: p.muted,
      textAlign: 'center',
      marginBottom: 1.5,
    },
    softwareFooterRuc: {
      fontSize: 7.6,
      color: p.muted,
      textAlign: 'center',
      letterSpacing: 0.3,
    },
  })
}

export type RideStyles = ReturnType<typeof createRideStyles>
