// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddCustomerRepairRateCards : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "customer_repair_rate_cards",
            schema: "repairs",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                rate_n1 = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                rate_n2 = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                rate_n3 = table.Column<decimal>(type: "numeric(18,4)", nullable: true),
                contract_reference = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                valid_from = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                created_by = table.Column<Guid>(type: "uuid", nullable: true),
                updated_by = table.Column<Guid>(type: "uuid", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_repair_rate_cards", x => x.id);
                table.ForeignKey(
                    name: "fk_customer_repair_rate_cards_customers_customer_id",
                    column: x => x.customer_id,
                    principalSchema: "repairs",
                    principalTable: "customers",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_repair_rate_cards_customer_id",
            schema: "repairs",
            table: "customer_repair_rate_cards",
            column: "customer_id");

        migrationBuilder.CreateIndex(
            name: "ix_customer_repair_rate_cards_tenant_id_customer_id",
            schema: "repairs",
            table: "customer_repair_rate_cards",
            columns: new[] { "tenant_id", "customer_id" },
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "customer_repair_rate_cards",
            schema: "repairs");
    }
}
