// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;
    /// <inheritdoc />
    public partial class AddRemisionGuidesModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "billing");

            migrationBuilder.CreateTable(
                name: "remision_guides",
                schema: "billing",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    establishment = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, defaultValue: "001"),
                    emission_point = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, defaultValue: "001"),
                    sequential = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                    access_key = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: false),
                    issue_date = table.Column<DateOnly>(type: "date", nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    authorization_number = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: true),
                    authorization_date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    sri_messages = table.Column<string>(type: "text", nullable: true),
                    xml_content = table.Column<string>(type: "text", nullable: true),
                    carrier_identification_type = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "04"),
                    carrier_identification = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    carrier_name = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    carrier_email = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: true),
                    carrier_phone = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    license_plate = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    starting_address = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    start_date = table.Column<DateOnly>(type: "date", nullable: false),
                    end_date = table.Column<DateOnly>(type: "date", nullable: false),
                    recipient_identification_type = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "04"),
                    recipient_identification = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    recipient_name = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    recipient_address = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    transfer_reason = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    route_description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    support_document_type = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: true),
                    support_document_number = table.Column<string>(type: "character varying(25)", maxLength: 25, nullable: true),
                    support_document_auth = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: true),
                    customs_document_number = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_remision_guides", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "remision_guide_items",
                schema: "billing",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    remision_guide_id = table.Column<Guid>(type: "uuid", nullable: false),
                    item_code = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    quantity = table.Column<decimal>(type: "numeric(18,4)", precision: 18, scale: 4, nullable: false),
                    unit_of_measure = table.Column<string>(type: "character varying(25)", maxLength: 25, nullable: true),
                    internal_reference = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_remision_guide_items", x => x.id);
                    table.ForeignKey(
                        name: "fk_remision_guide_items_remision_guides_remision_guide_id",
                        column: x => x.remision_guide_id,
                        principalSchema: "billing",
                        principalTable: "remision_guides",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_remision_guide_items_remision_guide_id",
                schema: "billing",
                table: "remision_guide_items",
                column: "remision_guide_id");

            migrationBuilder.CreateIndex(
                name: "ix_remision_guides_tenant_id_establishment_emission_point_sequ",
                schema: "billing",
                table: "remision_guides",
                columns: new[] { "tenant_id", "establishment", "emission_point", "sequential" },
                unique: true,
                filter: "deleted_at IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_remision_guides_tenant_id_issue_date",
                schema: "billing",
                table: "remision_guides",
                columns: new[] { "tenant_id", "issue_date" });

            migrationBuilder.CreateIndex(
                name: "ix_remision_guides_tenant_id_license_plate",
                schema: "billing",
                table: "remision_guides",
                columns: new[] { "tenant_id", "license_plate" });

            migrationBuilder.CreateIndex(
                name: "ix_remision_guides_tenant_id_status",
                schema: "billing",
                table: "remision_guides",
                columns: new[] { "tenant_id", "status" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "remision_guide_items",
                schema: "billing");

            migrationBuilder.DropTable(
                name: "remision_guides",
                schema: "billing");
        }
    }
