// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddVariantAttributeTyping : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "data_type",
                schema: "catalog",
                table: "variant_dimension_templates",
                type: "character varying(20)",
                maxLength: 20,
                nullable: false,
                defaultValue: "text");

            migrationBuilder.AddColumn<bool>(
                name: "is_variant_axis",
                schema: "catalog",
                table: "variant_dimension_templates",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<string>(
                name: "unit",
                schema: "catalog",
                table: "variant_dimension_templates",
                type: "character varying(20)",
                maxLength: 20,
                nullable: true);

            // Backfill: las escalas existentes con semántica de color se tipan como color.
            migrationBuilder.Sql(
                """
                UPDATE catalog.variant_dimension_templates
                SET data_type = 'color'
                WHERE data_type = 'text'
                  AND (dimension_type ILIKE '%color%' OR name ILIKE '%color%');
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "data_type",
                schema: "catalog",
                table: "variant_dimension_templates");

            migrationBuilder.DropColumn(
                name: "is_variant_axis",
                schema: "catalog",
                table: "variant_dimension_templates");

            migrationBuilder.DropColumn(
                name: "unit",
                schema: "catalog",
                table: "variant_dimension_templates");
        }
    }
}
