// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddCatalogItemImageGroupValue : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "group_value",
                schema: "catalog",
                table: "item_images",
                type: "character varying(120)",
                maxLength: 120,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_item_images_catalog_item_id_group_value",
                schema: "catalog",
                table: "item_images",
                columns: new[] { "catalog_item_id", "group_value" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_item_images_catalog_item_id_group_value",
                schema: "catalog",
                table: "item_images");

            migrationBuilder.DropColumn(
                name: "group_value",
                schema: "catalog",
                table: "item_images");
        }
    }
}
