// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddEcommerceOrderItemPricingSnapshot : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "applied_rules_json",
                schema: "ecommerce",
                table: "order_items",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "list_price",
                schema: "ecommerce",
                table: "order_items",
                type: "numeric(18,6)",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "price_list_id",
                schema: "ecommerce",
                table: "order_items",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_order_items_price_list_id",
                schema: "ecommerce",
                table: "order_items",
                column: "price_list_id");

            migrationBuilder.AddForeignKey(
                name: "fk_order_items_price_lists_price_list_id",
                schema: "ecommerce",
                table: "order_items",
                column: "price_list_id",
                principalSchema: "pricing",
                principalTable: "price_lists",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_order_items_price_lists_price_list_id",
                schema: "ecommerce",
                table: "order_items");

            migrationBuilder.DropIndex(
                name: "ix_order_items_price_list_id",
                schema: "ecommerce",
                table: "order_items");

            migrationBuilder.DropColumn(
                name: "applied_rules_json",
                schema: "ecommerce",
                table: "order_items");

            migrationBuilder.DropColumn(
                name: "list_price",
                schema: "ecommerce",
                table: "order_items");

            migrationBuilder.DropColumn(
                name: "price_list_id",
                schema: "ecommerce",
                table: "order_items");
        }
    }
}
