// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class FixSubscriptionAccountEntitlementsSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE tenancy.subscription_accounts ADD COLUMN IF NOT EXISTS last_entitlements_sync_at_utc timestamptz NULL;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE tenancy.subscription_accounts DROP COLUMN IF EXISTS last_entitlements_sync_at_utc;");
        }
    }
}
