// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddCatalogItemImages : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "item_images",
            schema: "catalog",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                catalog_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                storage_key = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                original_file_name = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                alt_text = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: true),
                display_order = table.Column<int>(type: "integer", nullable: false),
                is_main = table.Column<bool>(type: "boolean", nullable: false),
                original_width = table.Column<int>(type: "integer", nullable: false),
                original_height = table.Column<int>(type: "integer", nullable: false),
                file_size_bytes = table.Column<long>(type: "bigint", nullable: false),
                mime_type = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false, defaultValue: "image/webp"),
                thumb_url = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                medium_url = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                large_url = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                created_by = table.Column<Guid>(type: "uuid", nullable: true),
                updated_by = table.Column<Guid>(type: "uuid", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_item_images", x => x.id);
                table.ForeignKey(
                    name: "fk_item_images_items_catalog_item_id",
                    column: x => x.catalog_item_id,
                    principalSchema: "catalog",
                    principalTable: "items",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_item_images_catalog_item_id",
            schema: "catalog",
            table: "item_images",
            column: "catalog_item_id");

        migrationBuilder.CreateIndex(
            name: "ix_item_images_catalog_item_id_display_order",
            schema: "catalog",
            table: "item_images",
            columns: new[] { "catalog_item_id", "display_order" });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "item_images",
            schema: "catalog");
    }
}
