// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddEcommerceModule : Migration
{
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "ecommerce");

            migrationBuilder.AddColumn<decimal>(
                name: "reserved_quantity",
                schema: "inventory",
                table: "stocks",
                type: "numeric(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.CreateTable(
                name: "orders",
                schema: "ecommerce",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    order_number = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    warehouse_id = table.Column<Guid>(type: "uuid", nullable: false),
                    order_date = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    payment_status = table.Column<int>(type: "integer", nullable: false),
                    payment_method = table.Column<int>(type: "integer", nullable: false),
                    payment_reference = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    shipping_method = table.Column<int>(type: "integer", nullable: false),
                    subtotal = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    discount_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    tax_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    shipping_cost = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    total_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    billing_invoice_id = table.Column<Guid>(type: "uuid", nullable: true),
                    estimated_delivery_date = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    shipped_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    delivered_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    cancelled_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    cancellation_reason = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    internal_notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    customer_notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                    customer_address = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    customer_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    customer_email = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    customer_phone = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    customer_tax_id = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    customer_tax_id_type = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: true),
                    shipping_address_line1 = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    shipping_address_line2 = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true),
                    shipping_carrier = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    shipping_city = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    shipping_notes = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    shipping_postal_code = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    shipping_province = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    shipping_recipient_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    shipping_recipient_phone = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    shipping_tracking_number = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_orders", x => x.id);
                    table.ForeignKey(
                        name: "fk_orders_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalSchema: "tenancy",
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_orders_warehouses_warehouse_id",
                        column: x => x.warehouse_id,
                        principalSchema: "warehousing",
                        principalTable: "warehouses",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "order_items",
                schema: "ecommerce",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ecommerce_order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    catalog_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                    sku = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    item_name = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: false),
                    quantity = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    unit_price = table.Column<decimal>(type: "numeric(18,4)", nullable: false),
                    discount_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    tax_rate = table.Column<decimal>(type: "numeric(6,4)", nullable: false),
                    tax_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    total_amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_order_items", x => x.id);
                    table.ForeignKey(
                        name: "fk_order_items_items_catalog_item_id",
                        column: x => x.catalog_item_id,
                        principalSchema: "catalog",
                        principalTable: "items",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_order_items_orders_ecommerce_order_id",
                        column: x => x.ecommerce_order_id,
                        principalSchema: "ecommerce",
                        principalTable: "orders",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "order_timelines",
                schema: "ecommerce",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ecommerce_order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    previous_status = table.Column<int>(type: "integer", nullable: true),
                    new_status = table.Column<int>(type: "integer", nullable: false),
                    notes = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    occurred_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    user_name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_order_timelines", x => x.id);
                    table.ForeignKey(
                        name: "fk_order_timelines_orders_ecommerce_order_id",
                        column: x => x.ecommerce_order_id,
                        principalSchema: "ecommerce",
                        principalTable: "orders",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_order_items_catalog_item_id",
                schema: "ecommerce",
                table: "order_items",
                column: "catalog_item_id");

            migrationBuilder.CreateIndex(
                name: "ix_order_items_ecommerce_order_id",
                schema: "ecommerce",
                table: "order_items",
                column: "ecommerce_order_id");

            migrationBuilder.CreateIndex(
                name: "ix_order_timelines_ecommerce_order_id",
                schema: "ecommerce",
                table: "order_timelines",
                column: "ecommerce_order_id");

            migrationBuilder.CreateIndex(
                name: "ix_order_timelines_occurred_at",
                schema: "ecommerce",
                table: "order_timelines",
                column: "occurred_at");

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_id_billing_invoice_id",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "tenant_id", "billing_invoice_id" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_id_order_date",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "tenant_id", "order_date" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_id_order_number",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "tenant_id", "order_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_id_status",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "tenant_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_warehouse_id",
                schema: "ecommerce",
                table: "orders",
                column: "warehouse_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "order_items",
                schema: "ecommerce");

            migrationBuilder.DropTable(
                name: "order_timelines",
                schema: "ecommerce");

            migrationBuilder.DropTable(
                name: "orders",
                schema: "ecommerce");

            migrationBuilder.DropColumn(
                name: "reserved_quantity",
                schema: "inventory",
                table: "stocks");
        }
    }
