// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddEcommerceOrderClientRequestId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "client_request_id",
                schema: "ecommerce",
                table: "orders",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_orders_status_payment_status_order_date",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "status", "payment_status", "order_date" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_id_client_request_id",
                schema: "ecommerce",
                table: "orders",
                columns: new[] { "tenant_id", "client_request_id" },
                unique: true,
                filter: "client_request_id IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_orders_status_payment_status_order_date",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropIndex(
                name: "ix_orders_tenant_id_client_request_id",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "client_request_id",
                schema: "ecommerce",
                table: "orders");
        }
    }
}
