// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddEcommerceOrderPaymentProof : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "payment_proof_content_type",
                schema: "ecommerce",
                table: "orders",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "payment_proof_object_key",
                schema: "ecommerce",
                table: "orders",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "payment_proof_token",
                schema: "ecommerce",
                table: "orders",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "payment_proof_uploaded_at_utc",
                schema: "ecommerce",
                table: "orders",
                type: "timestamptz",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_orders_payment_proof_token",
                schema: "ecommerce",
                table: "orders",
                column: "payment_proof_token",
                unique: true,
                filter: "payment_proof_token <> ''");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_orders_payment_proof_token",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "payment_proof_content_type",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "payment_proof_object_key",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "payment_proof_token",
                schema: "ecommerce",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "payment_proof_uploaded_at_utc",
                schema: "ecommerce",
                table: "orders");
        }
    }
}
