// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddShippingZonesAndMethods : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "shipping_methods",
                schema: "logistics",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    code = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true),
                    estimated_days = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: true),
                    sort_order = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_shipping_methods", x => x.id);
                    table.ForeignKey(
                        name: "fk_shipping_methods_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalSchema: "tenancy",
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "shipping_zones",
                schema: "logistics",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    code = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true),
                    provinces = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    sort_order = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_shipping_zones", x => x.id);
                    table.ForeignKey(
                        name: "fk_shipping_zones_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalSchema: "tenancy",
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_shipping_rate_rules_shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                column: "shipping_method_id");

            migrationBuilder.CreateIndex(
                name: "ix_shipping_rate_rules_shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                column: "shipping_zone_id");

            migrationBuilder.CreateIndex(
                name: "ix_shipping_methods_tenant_code",
                schema: "logistics",
                table: "shipping_methods",
                columns: new[] { "tenant_id", "code" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_shipping_zones_tenant_code",
                schema: "logistics",
                table: "shipping_zones",
                columns: new[] { "tenant_id", "code" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_shipping_rate_rules_shipping_methods_shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                column: "shipping_method_id",
                principalSchema: "logistics",
                principalTable: "shipping_methods",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "fk_shipping_rate_rules_shipping_zones_shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules",
                column: "shipping_zone_id",
                principalSchema: "logistics",
                principalTable: "shipping_zones",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_shipping_rate_rules_shipping_methods_shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules");

            migrationBuilder.DropForeignKey(
                name: "fk_shipping_rate_rules_shipping_zones_shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules");

            migrationBuilder.DropTable(
                name: "shipping_methods",
                schema: "logistics");

            migrationBuilder.DropTable(
                name: "shipping_zones",
                schema: "logistics");

            migrationBuilder.DropIndex(
                name: "ix_shipping_rate_rules_shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules");

            migrationBuilder.DropIndex(
                name: "ix_shipping_rate_rules_shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules");

            migrationBuilder.DropColumn(
                name: "shipping_method_id",
                schema: "logistics",
                table: "shipping_rate_rules");

            migrationBuilder.DropColumn(
                name: "shipping_zone_id",
                schema: "logistics",
                table: "shipping_rate_rules");
        }
    }
}
