// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddCustomerClassificationColumns : Migration
{
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "customer_type",
                schema: "repairs",
                table: "customers",
                type: "integer",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.AddColumn<int>(
                name: "identification_type",
                schema: "repairs",
                table: "customers",
                type: "integer",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.CreateIndex(
                name: "ix_customers_tenant_id_customer_type",
                schema: "repairs",
                table: "customers",
                columns: new[] { "tenant_id", "customer_type" },
                filter: "\"deleted_at\" IS NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_customers_tenant_id_customer_type",
                schema: "repairs",
                table: "customers");

            migrationBuilder.DropColumn(
                name: "customer_type",
                schema: "repairs",
                table: "customers");

            migrationBuilder.DropColumn(
                name: "identification_type",
                schema: "repairs",
                table: "customers");
        }
}
