// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class BackfillPricingFromBasePrice : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                INSERT INTO pricing.price_lists
                    (id, tenant_id, code, name, description, currency, prices_include_tax, valid_from, valid_to, priority, is_default, is_active, created_at)
                SELECT
                    gen_random_uuid(),
                    t.id,
                    'PUBLICO',
                    'Precio publico',
                    'Lista predeterminada creada por la migracion de precios',
                    'USD',
                    false,
                    CURRENT_DATE,
                    NULL,
                    0,
                    true,
                    true,
                    now()
                FROM tenancy.tenants t
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM pricing.price_lists l
                    WHERE l.tenant_id = t.id AND l.code = 'PUBLICO'
                );
                """);

            migrationBuilder.Sql(
                """
                INSERT INTO pricing.product_prices
                    (id, tenant_id, price_list_id, catalog_item_id, price, valid_from, valid_to, is_active, created_at)
                SELECT
                    gen_random_uuid(),
                    i.tenant_id,
                    l.id,
                    i.id,
                    i.base_price,
                    CURRENT_DATE,
                    NULL,
                    true,
                    now()
                FROM catalog.items i
                JOIN pricing.price_lists l
                    ON l.tenant_id = i.tenant_id
                    AND l.code = 'PUBLICO'
                    AND l.is_active
                WHERE i.kind = 0
                    AND i.status = 0
                    AND i.deleted_at IS NULL
                    AND i.parent_id IS NULL
                    AND i.base_price IS NOT NULL
                    AND i.base_price >= 0
                    AND NOT EXISTS (
                        SELECT 1
                        FROM pricing.product_prices p
                        WHERE p.tenant_id = i.tenant_id
                            AND p.price_list_id = l.id
                            AND p.catalog_item_id = i.id
                    );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // La carga de datos históricos no se revierte automáticamente.
        }
    }
}
