// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddCreditNotesModule : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "credit_notes",
            schema: "billing",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                establishment = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, defaultValue: "001"),
                emission_point = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false, defaultValue: "001"),
                sequential = table.Column<string>(type: "character varying(9)", maxLength: 9, nullable: false),
                access_key = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: false),
                issue_date = table.Column<DateOnly>(type: "date", nullable: false),
                status = table.Column<int>(type: "integer", nullable: false),
                reason_type = table.Column<int>(type: "integer", nullable: false),
                reason = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                modified_document_type = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "01"),
                modified_document_number = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                modified_document_issue_date = table.Column<DateOnly>(type: "date", nullable: false),
                modified_document_authorization_number = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: true),
                modified_document_id = table.Column<Guid>(type: "uuid", nullable: true),
                buyer_identification_type = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "04"),
                buyer_identification = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                buyer_name = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                buyer_address = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                buyer_email = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: true),
                subtotal_without_taxes = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                total_discount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_vat15 = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_vat13 = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_vat12 = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_vat0 = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_no_vat = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal_exempt_vat = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                vat_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                modification_value = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                environment = table.Column<string>(type: "character varying(1)", maxLength: 1, nullable: false, defaultValue: "1"),
                authorization_number = table.Column<string>(type: "character varying(49)", maxLength: 49, nullable: true),
                authorization_date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                sri_messages = table.Column<string>(type: "text", nullable: true),
                xml_content = table.Column<string>(type: "text", nullable: true),
                additional_fields = table.Column<string>(type: "jsonb", nullable: true),
                created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                created_by = table.Column<Guid>(type: "uuid", nullable: true),
                updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                deleted_by = table.Column<Guid>(type: "uuid", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_credit_notes", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "credit_note_items",
            schema: "billing",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                credit_note_id = table.Column<Guid>(type: "uuid", nullable: false),
                line_number = table.Column<int>(type: "integer", nullable: false),
                item_code = table.Column<string>(type: "character varying(25)", maxLength: 25, nullable: false),
                additional_code = table.Column<string>(type: "character varying(25)", maxLength: 25, nullable: true),
                description = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                quantity = table.Column<decimal>(type: "numeric(18,6)", precision: 18, scale: 6, nullable: false),
                unit_price = table.Column<decimal>(type: "numeric(18,6)", precision: 18, scale: 6, nullable: false),
                discount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                subtotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                vat_code = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "2"),
                vat_percentage_code = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false, defaultValue: "4"),
                vat_rate = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                vat_base = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                vat_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                total = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                warehouse_id = table.Column<Guid>(type: "uuid", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_credit_note_items", x => x.id);
                table.ForeignKey(
                    name: "fk_credit_note_items_credit_notes_credit_note_id",
                    column: x => x.credit_note_id,
                    principalSchema: "billing",
                    principalTable: "credit_notes",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_credit_note_items_credit_note_id",
            schema: "billing",
            table: "credit_note_items",
            column: "credit_note_id");

        migrationBuilder.CreateIndex(
            name: "ix_credit_notes_tenant_id_buyer_identification",
            schema: "billing",
            table: "credit_notes",
            columns: new[] { "tenant_id", "buyer_identification" });

        migrationBuilder.CreateIndex(
            name: "ix_credit_notes_tenant_id_establishment_emission_point_sequent",
            schema: "billing",
            table: "credit_notes",
            columns: new[] { "tenant_id", "establishment", "emission_point", "sequential" },
            unique: true,
            filter: "deleted_at IS NULL");

        migrationBuilder.CreateIndex(
            name: "ix_credit_notes_tenant_id_issue_date",
            schema: "billing",
            table: "credit_notes",
            columns: new[] { "tenant_id", "issue_date" });

        migrationBuilder.CreateIndex(
            name: "ix_credit_notes_tenant_id_modified_document_number",
            schema: "billing",
            table: "credit_notes",
            columns: new[] { "tenant_id", "modified_document_number" });

        migrationBuilder.CreateIndex(
            name: "ix_credit_notes_tenant_id_status",
            schema: "billing",
            table: "credit_notes",
            columns: new[] { "tenant_id", "status" });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "credit_note_items",
            schema: "billing");

        migrationBuilder.DropTable(
            name: "credit_notes",
            schema: "billing");
    }
}
