// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddCatalogItemFamilyAndHierarchyPath : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "family_id",
                schema: "catalog",
                table: "items",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "hierarchy_path_json",
                schema: "catalog",
                table: "items",
                type: "jsonb",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_items_family_id",
                schema: "catalog",
                table: "items",
                column: "family_id");

            migrationBuilder.CreateIndex(
                name: "ix_items_hierarchy_path_json",
                schema: "catalog",
                table: "items",
                column: "hierarchy_path_json")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "ix_items_tenant_id_family_id",
                schema: "catalog",
                table: "items",
                columns: new[] { "tenant_id", "family_id" },
                filter: "\"deleted_at\" IS NULL");

            migrationBuilder.AddForeignKey(
                name: "fk_items_product_templates_family_id",
                schema: "catalog",
                table: "items",
                column: "family_id",
                principalSchema: "catalog",
                principalTable: "product_templates",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_items_product_templates_family_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropIndex(
                name: "ix_items_family_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropIndex(
                name: "ix_items_hierarchy_path_json",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropIndex(
                name: "ix_items_tenant_id_family_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropColumn(
                name: "family_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropColumn(
                name: "hierarchy_path_json",
                schema: "catalog",
                table: "items");
        }
    }
}
