// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddRepairsModule : Migration
{
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "repairs");

            migrationBuilder.CreateTable(
                name: "customers",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    tax_id = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    contact_email = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                    contact_phone = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: true),
                    address = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true),
                    contact_person = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                    notes = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    deleted_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_customers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "batch_templates",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    customer_id = table.Column<Guid>(type: "uuid", nullable: true),
                    name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    column_definitions_json = table.Column<string>(type: "jsonb", nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_batch_templates", x => x.id);
                    table.ForeignKey(
                        name: "fk_batch_templates_customers_customer_id",
                        column: x => x.customer_id,
                        principalSchema: "repairs",
                        principalTable: "customers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "batches",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                    template_id = table.Column<Guid>(type: "uuid", nullable: true),
                    batch_number = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    total_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    received_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    in_repair_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    ready_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    dispatched_count = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    agreed_rate_n1 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    agreed_rate_n2 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    agreed_rate_n3 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    contract_reference = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    expected_completion_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    received_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    metadata_json = table.Column<string>(type: "jsonb", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_batches", x => x.id);
                    table.ForeignKey(
                        name: "fk_batches_customers_customer_id",
                        column: x => x.customer_id,
                        principalSchema: "repairs",
                        principalTable: "customers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_batches_repair_batch_templates_template_id",
                        column: x => x.template_id,
                        principalSchema: "repairs",
                        principalTable: "batch_templates",
                        principalColumn: "id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "dispatches",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    batch_id = table.Column<Guid>(type: "uuid", nullable: false),
                    dispatch_number = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    carrier_name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                    carrier_document = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true),
                    carrier_vehicle_plate = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    verification_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    qr_code_url = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    notes = table.Column<string>(type: "text", nullable: true),
                    invoice_id = table.Column<Guid>(type: "uuid", nullable: true),
                    dispatched_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_dispatches", x => x.id);
                    table.ForeignKey(
                        name: "fk_dispatches_batches_batch_id",
                        column: x => x.batch_id,
                        principalSchema: "repairs",
                        principalTable: "batches",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "equipments",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    batch_id = table.Column<Guid>(type: "uuid", nullable: false),
                    assigned_technician_id = table.Column<Guid>(type: "uuid", nullable: true),
                    serial_number = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    model = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    brand = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    product_line = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: true),
                    damage_level = table.Column<int>(type: "integer", nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    diagnostic_notes = table.Column<string>(type: "text", nullable: true),
                    repair_notes = table.Column<string>(type: "text", nullable: true),
                    quality_check_notes = table.Column<string>(type: "text", nullable: true),
                    passed_quality_check = table.Column<bool>(type: "boolean", nullable: true),
                    diagnosed_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    repaired_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    quality_checked_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    service_fee_applied = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    custom_attributes_json = table.Column<string>(type: "jsonb", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_equipments", x => x.id);
                    table.ForeignKey(
                        name: "fk_equipments_batches_batch_id",
                        column: x => x.batch_id,
                        principalSchema: "repairs",
                        principalTable: "batches",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "dispatch_items",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    dispatch_id = table.Column<Guid>(type: "uuid", nullable: false),
                    equipment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_dispatch_items", x => x.id);
                    table.ForeignKey(
                        name: "fk_dispatch_items_dispatches_dispatch_id",
                        column: x => x.dispatch_id,
                        principalSchema: "repairs",
                        principalTable: "dispatches",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_dispatch_items_repair_equipments_equipment_id",
                        column: x => x.equipment_id,
                        principalSchema: "repairs",
                        principalTable: "equipments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "equipment_events",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    equipment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    from_status = table.Column<int>(type: "integer", nullable: false),
                    to_status = table.Column<int>(type: "integer", nullable: false),
                    note = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    occurred_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_equipment_events", x => x.id);
                    table.ForeignKey(
                        name: "fk_equipment_events_equipments_equipment_id",
                        column: x => x.equipment_id,
                        principalSchema: "repairs",
                        principalTable: "equipments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "equipment_photos",
                schema: "repairs",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    equipment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    uploaded_by = table.Column<Guid>(type: "uuid", nullable: true),
                    stage = table.Column<int>(type: "integer", nullable: false),
                    s3bucket = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    s3key = table.Column<string>(type: "character varying(400)", maxLength: 400, nullable: false),
                    file_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    content_type = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, defaultValue: "image/webp"),
                    file_size_bytes = table.Column<long>(type: "bigint", nullable: false),
                    caption = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: true),
                    captured_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_equipment_photos", x => x.id);
                    table.ForeignKey(
                        name: "fk_equipment_photos_equipments_equipment_id",
                        column: x => x.equipment_id,
                        principalSchema: "repairs",
                        principalTable: "equipments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_batch_templates_customer_id",
                schema: "repairs",
                table: "batch_templates",
                column: "customer_id");

            migrationBuilder.CreateIndex(
                name: "ix_batch_templates_tenant_id_name",
                schema: "repairs",
                table: "batch_templates",
                columns: new[] { "tenant_id", "name" });

            migrationBuilder.CreateIndex(
                name: "ix_batches_customer_id",
                schema: "repairs",
                table: "batches",
                column: "customer_id");

            migrationBuilder.CreateIndex(
                name: "ix_batches_template_id",
                schema: "repairs",
                table: "batches",
                column: "template_id");

            migrationBuilder.CreateIndex(
                name: "ix_batches_tenant_id_batch_number",
                schema: "repairs",
                table: "batches",
                columns: new[] { "tenant_id", "batch_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_batches_tenant_id_customer_id",
                schema: "repairs",
                table: "batches",
                columns: new[] { "tenant_id", "customer_id" });

            migrationBuilder.CreateIndex(
                name: "ix_batches_tenant_id_status",
                schema: "repairs",
                table: "batches",
                columns: new[] { "tenant_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_customers_tenant_id_name",
                schema: "repairs",
                table: "customers",
                columns: new[] { "tenant_id", "name" });

            migrationBuilder.CreateIndex(
                name: "ix_customers_tenant_id_tax_id",
                schema: "repairs",
                table: "customers",
                columns: new[] { "tenant_id", "tax_id" });

            migrationBuilder.CreateIndex(
                name: "ix_dispatch_items_dispatch_id_equipment_id",
                schema: "repairs",
                table: "dispatch_items",
                columns: new[] { "dispatch_id", "equipment_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_dispatch_items_equipment_id",
                schema: "repairs",
                table: "dispatch_items",
                column: "equipment_id");

            migrationBuilder.CreateIndex(
                name: "ix_dispatches_batch_id_status",
                schema: "repairs",
                table: "dispatches",
                columns: new[] { "batch_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_dispatches_tenant_id_dispatch_number",
                schema: "repairs",
                table: "dispatches",
                columns: new[] { "tenant_id", "dispatch_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_dispatches_verification_hash",
                schema: "repairs",
                table: "dispatches",
                column: "verification_hash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_equipment_events_equipment_id_occurred_at",
                schema: "repairs",
                table: "equipment_events",
                columns: new[] { "equipment_id", "occurred_at" });

            migrationBuilder.CreateIndex(
                name: "ix_equipment_photos_equipment_id_stage",
                schema: "repairs",
                table: "equipment_photos",
                columns: new[] { "equipment_id", "stage" });

            migrationBuilder.CreateIndex(
                name: "ix_equipments_batch_id_status",
                schema: "repairs",
                table: "equipments",
                columns: new[] { "batch_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_equipments_custom_attributes_json",
                schema: "repairs",
                table: "equipments",
                column: "custom_attributes_json")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "ix_equipments_tenant_id_serial_number",
                schema: "repairs",
                table: "equipments",
                columns: new[] { "tenant_id", "serial_number" });

            migrationBuilder.CreateIndex(
                name: "ix_equipments_tenant_id_status",
                schema: "repairs",
                table: "equipments",
                columns: new[] { "tenant_id", "status" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "dispatch_items",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "equipment_events",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "equipment_photos",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "dispatches",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "equipments",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "batches",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "batch_templates",
                schema: "repairs");

            migrationBuilder.DropTable(
                name: "customers",
                schema: "repairs");
        }
    }
