// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddProductPriceOverlapConstraint : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    CREATE EXTENSION IF NOT EXISTS btree_gist;
                    ALTER TABLE pricing.product_prices
                        ADD CONSTRAINT ex_product_prices_no_overlap
                        EXCLUDE USING gist (
                            tenant_id WITH =,
                            price_list_id WITH =,
                            catalog_item_id WITH =,
                            daterange(valid_from, COALESCE(valid_to, 'infinity'::date), '[]') WITH &&
                        ) WHERE (is_active);
                EXCEPTION
                    WHEN insufficient_privilege THEN
                        RAISE WARNING 'No se pudo crear btree_gist/ex_product_prices_no_overlap: %', SQLERRM;
                    WHEN duplicate_object THEN
                        RAISE NOTICE 'La restriccion ex_product_prices_no_overlap ya existe.';
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE pricing.product_prices DROP CONSTRAINT IF EXISTS ex_product_prices_no_overlap;");
        }
    }
}
