// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddCatalogJsonbAndVariantIndexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "ix_items_custom_attributes_json",
                schema: "catalog",
                table: "items",
                column: "custom_attributes_json")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                name: "ix_items_tenant_id_parent_id",
                schema: "catalog",
                table: "items",
                columns: new[] { "tenant_id", "parent_id" },
                filter: "\"deleted_at\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_items_variant_dimensions_json",
                schema: "catalog",
                table: "items",
                column: "variant_dimensions_json")
                .Annotation("Npgsql:IndexMethod", "gin");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_items_custom_attributes_json",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropIndex(
                name: "ix_items_tenant_id_parent_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropIndex(
                name: "ix_items_variant_dimensions_json",
                schema: "catalog",
                table: "items");
        }
    }
}
