// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddTenantSigningCertificates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tenant_signing_certificates",
                schema: "tenancy",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    encrypted_data = table.Column<byte[]>(type: "bytea", nullable: false),
                    encrypted_password = table.Column<byte[]>(type: "bytea", nullable: false),
                    nonce = table.Column<byte[]>(type: "bytea", nullable: false),
                    tag = table.Column<byte[]>(type: "bytea", nullable: false),
                    subject = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    subject_tax_id = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    issuer = table.Column<string>(type: "character varying(300)", maxLength: 300, nullable: false),
                    valid_from = table.Column<DateTime>(type: "timestamptz", nullable: false),
                    valid_to = table.Column<DateTime>(type: "timestamptz", nullable: false),
                    serial_number = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                    original_file_name = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    created_by = table.Column<Guid>(type: "uuid", maxLength: 200, nullable: true),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", maxLength: 200, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tenant_signing_certificates", x => x.id);
                    table.ForeignKey(
                        name: "fk_tenant_signing_certificates_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalSchema: "tenancy",
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_tenant_signing_certificates_tenant_id",
                schema: "tenancy",
                table: "tenant_signing_certificates",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_tenant_signing_certificates_tenant_id_is_active",
                schema: "tenancy",
                table: "tenant_signing_certificates",
                columns: new[] { "tenant_id", "is_active" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "tenant_signing_certificates",
                schema: "tenancy");
        }
    }
