// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0005
#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace EcuNexo.Data.Migrations;

/// <inheritdoc />
public partial class AddProductMatrixAndVariantTemplates : Migration
{
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "is_matrix_parent",
                schema: "catalog",
                table: "items",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<Guid>(
                name: "parent_id",
                schema: "catalog",
                table: "items",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "variant_dimensions_json",
                schema: "catalog",
                table: "items",
                type: "jsonb",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "variant_dimension_templates",
                schema: "catalog",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    dimension_type = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    predefined_values_json = table.Column<string>(type: "jsonb", nullable: false),
                    is_system_default = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamptz", nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_variant_dimension_templates", x => x.id);
                    table.ForeignKey(
                        name: "fk_variant_dimension_templates_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalSchema: "tenancy",
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_items_parent_id",
                schema: "catalog",
                table: "items",
                column: "parent_id");

            migrationBuilder.CreateIndex(
                name: "ix_variant_dimension_templates_tenant_id_name",
                schema: "catalog",
                table: "variant_dimension_templates",
                columns: new[] { "tenant_id", "name" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_items_items_parent_id",
                schema: "catalog",
                table: "items",
                column: "parent_id",
                principalSchema: "catalog",
                principalTable: "items",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_items_items_parent_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropTable(
                name: "variant_dimension_templates",
                schema: "catalog");

            migrationBuilder.DropIndex(
                name: "ix_items_parent_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropColumn(
                name: "is_matrix_parent",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropColumn(
                name: "parent_id",
                schema: "catalog",
                table: "items");

            migrationBuilder.DropColumn(
                name: "variant_dimensions_json",
                schema: "catalog",
                table: "items");
    }
}
