import type { ReactElement } from 'react'
import {
  BarChart3,
  Building2,
  Calculator,
  Check,
  CirclePlus,
  Copy,
  Eye,
  FileText,
  FolderTree,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Library,
  LogOut,
  Moon,
  Package,
  Pencil,
  Plus,
  Receipt,
  RefreshCw,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  Truck,
  UserPlus,
  UserX,
  Users,
  Warehouse,
  Wrench,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  'building-2': Building2,
  'circle-plus': CirclePlus,
  plus: Plus,
  add_business: Plus,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  analytics: BarChart3,
  'bar-chart-3': BarChart3,
  domain: Building2,
  settings: Settings,
  'sliders-horizontal': SlidersHorizontal,
  group: Users,
  users: Users,
  'user-plus': UserPlus,
  'user-x': UserX,
  pencil: Pencil,
  'trash-2': Trash2,
  shield: Shield,
  'folder-tree': FolderTree,
  folder_tree: FolderTree,
  category: FolderTree,
  key: Key,
  package: Package,
  receipt: Receipt,
  library: Library,
  calculator: Calculator,
  'file-text': FileText,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  admin_panel_settings: ShieldCheck,
  inventory_2: Package,
  warehouse: Warehouse,
  list: FileText,
  sparkles: Sparkles,
  auto_awesome: Sparkles,
  copy: Copy,
  content_copy: Copy,
  info: Info,
  logout: LogOut,
  'log-out': LogOut,
  light_mode: Sun,
  dark_mode: Moon,
  sun: Sun,
  moon: Moon,
  check: Check,
  build: Wrench,
  wrench: Wrench,
  layers: Layers,
  truck: Truck,
  eye: Eye,
}

export function renderSidebarIcon(name: string, className?: string): ReactElement | null {
  const Icon = iconMap[name]
  return Icon ? <Icon className={className} aria-hidden /> : null
}
