import type { ReactElement } from 'react'
import {
  BarChart3,
  Building2,
  Calculator,
  CirclePlus,
  FileText,
  FolderTree,
  Key,
  LayoutDashboard,
  Library,
  Package,
  Pencil,
  Plus,
  Receipt,
  RefreshCw,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Trash2,
  UserPlus,
  UserX,
  Users,
  Warehouse,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  'building-2': Building2,
  'circle-plus': CirclePlus,
  plus: Plus,
  add_business: Plus,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  analytics: BarChart3,
  'bar-chart-3': BarChart3,
  domain: Building2,
  settings: Settings,
  'sliders-horizontal': SlidersHorizontal,
  group: Users,
  users: Users,
  'user-plus': UserPlus,
  'user-x': UserX,
  pencil: Pencil,
  'trash-2': Trash2,
  shield: Shield,
  'folder-tree': FolderTree,
  key: Key,
  package: Package,
  receipt: Receipt,
  library: Library,
  calculator: Calculator,
  'file-text': FileText,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  admin_panel_settings: ShieldCheck,
  inventory_2: Package,
  warehouse: Warehouse,
  list: FileText,
}

export function renderSidebarIcon(name: string, className?: string): ReactElement | null {
  const Icon = iconMap[name]
  return Icon ? <Icon className={className} aria-hidden /> : null
}
